# MB of memory per core
memory: 170000

# Maximum allowed solving time per problem in seconds
timeout: 240

# Number of concurrent evaluations running
processes: 1

# For compilation tasks, number of concurrent AllSMT processes per task that enumerates
# total truth assignments
allsmt_processes: 14

# Benchmarks
benchmarks: [
  # Base test cases
  "data/benchmark/planning/h3/Painter"
  # "data/benchmark/ldd_randgen",
  # "data/benchmark/randgen"
] 

# T-Lemmas base path
tlemmas_dir: "data/results/planning_h3_parallel/planning_h3_1Prob_45Procs"

# Output dir, add a / to the end
results: "results/"